
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    firebaseConfig: { 
        apiKey: 'AIzaSyBPJK0wgdh0K1cNqh-3ReFW29_iBklbMiY',
        authDomain: 'imageuploaderapp-537b8.firebaseapp.com',
        databaseURL: 'https://imageuploaderapp-537b8-default-rtdb.firebaseio.com',
        projectId: 'imageuploaderapp-537b8',
        storageBucket: 'imageuploaderapp-537b8.appspot.com',
        messagingSenderId: '360385508704',
        appId: '1:360385508704:web:a68eaf671a4a8ae3c35a05',
        measurementId: 'G-YETE3JCDJ1'
    } 
  };
